// <auto-generated />
using System;
using FlightCrew.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightCrew.Infrastructure.Migrations
{
    [DbContext(typeof(FlightCrewDbContext))]
    [Migration("20250709082134_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightCrew.Domain.Entities.Pilot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeniorityLevel")
                        .HasColumnType("int");

                    b.Property<int>("VehicleRestriction")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pilots", (string)null);
                });

            modelBuilder.Entity("FlightCrew.Domain.Entities.Pilot", b =>
                {
                    b.OwnsOne("FlightCrew.Domain.ValueObjects.PilotInfo", "Info", b1 =>
                        {
                            b1.Property<Guid>("PilotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Age")
                                .HasColumnType("int");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("Nationality")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("PilotId");

                            b1.ToTable("Pilots");

                            b1.WithOwner()
                                .HasForeignKey("PilotId");

                            b1.OwnsMany("FlightCrew.Domain.ValueObjects.Language", "KnownLanguages", b2 =>
                                {
                                    b2.Property<Guid>("PilotInfoPilotId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(5)
                                        .HasColumnType("nvarchar(5)");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)");

                                    b2.HasKey("PilotInfoPilotId", "Id");

                                    b2.ToTable("PilotLanguages", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("PilotInfoPilotId");
                                });

                            b1.Navigation("KnownLanguages");
                        });

                    b.OwnsOne("FlightCrew.Domain.ValueObjects.Range", "AllowedRange", b1 =>
                        {
                            b1.Property<Guid>("PilotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Distance")
                                .HasColumnType("float");

                            b1.HasKey("PilotId");

                            b1.ToTable("Pilots");

                            b1.WithOwner()
                                .HasForeignKey("PilotId");
                        });

                    b.Navigation("AllowedRange")
                        .IsRequired();

                    b.Navigation("Info")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
